INSERT INTO `nodes_config` (`name`, `value`, `text`, `type`) VALUES
('template', 'default', 'Template', 'string'),
('default', 'content.php', 'System', 'string'),
('debug', '0', 'Debug mode', 'bool'),
('cron', '1', 'jQuery cron', 'bool'),
('compress', '1', 'Compress HTML', 'bool'),
('sandbox', '1', 'Sandbox payment mode', 'bool'),
('autoupdate', '1', 'Engine auto-update', 'bool'),
('autobackup', '1', 'Auto backup', 'bool'),
('backup_files', '0', 'Backup files', 'bool'),
('free_message', '0', 'Messages between users', 'bool'),
('daily_report', '1', 'Daily report to email', 'bool'),
('send_comments_email', '1', 'Email admin on comment', 'bool'),
('send_registration_email', '1', 'Email user on sign up', 'bool'),
('send_message_email', '1', 'Email user on message', 'bool'),
('send_paypal_email', '1', 'Email user on payment', 'bool'),
('paypal_test', '1', 'PayPal test mode', 'bool'),
('paypal_id', '', 'PayPal user ID', 'string'),
('paypal_description', '', 'PayPal description', 'string'),
('vk_link', 'https://vk.com', 'VK page URL', 'string'),
('vk_id', '', 'VK client ID', 'string'),
('fb_link', 'https://facebook.com', 'Facebook page URL', 'string'),
('fb_id', '', 'Facebook client ID', 'string'),
('fb_secret', '', 'Facebook client secret', 'string'),
('tw_link', 'https://twitter.com/', 'Twitter page URL', 'string'),
('tw_key', '', 'Twitter consumer key', 'string'),
('tw_secret', '', 'Twitter consumer secret', 'string'),
('gp_link', 'https://plus.google.com', 'Google+ page URL', 'string'),
('gp_id', '0', 'Google+ user ID', 'string'),
('gp_secret', '', 'Google+ client secret', 'string'),
('gp_dev', '', 'Google+ developer key', 'string'),
('backup_interval', '10', 'Day interval of backup', 'int'),
('token_limit', '20', 'Max queries \\ minute from session', 'int'),
('ip_limit', '60', 'Max queries \\ minute from IP', 'int'),
('outbox_limit', '1', 'Max outbox \\ minute', 'int'),
('version', '1', 'System', 'int'),
('lastupdate', '0', 'System', 'int'),
('checkupdate', '0', 'System', 'int'),
('cron_session', '0', 'System', 'int'),
('cron_images', '0', 'System', 'int'),
('cron_exec', '0', 'System', 'int'),
('cron_done', '0', 'System', 'int'),
('lastreport', '0', 'System', 'int'),
('backup_limit', '3', 'System', 'int'),
('backup_date', '0', 'System', 'int');

CREATE TABLE IF NOT EXISTS `nodes_attendance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cache_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `token` varchar(32) NOT NULL,
  `ref_id` int(11) NOT NULL,
  `ip` varchar(20) NOT NULL,
  `agent_id` int(11) NOT NULL,
  `date` int(11) NOT NULL,
  `display` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_backend` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mode` varchar(400) DEFAULT NULL,
  `file` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `nodes_backend` (`mode`, `file`) VALUES
('', 'main.php'),
('admin', 'admin.php'),
('account', 'account.php'),
('register', 'register.php'),
('login', 'login.php'),
('content', 'content.php'),
('product', 'product.php'),
('search', 'search.php'),
('profile', 'profile.php');

CREATE TABLE IF NOT EXISTS `nodes_cache` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(400) NOT NULL,
  `title` varchar(100) NOT NULL,
  `date` int(11) NOT NULL,
  `lang` varchar(3) NOT NULL,
  `interval` int(11) NOT NULL,
  `html` longtext NOT NULL,
  `description` varchar(200) NOT NULL DEFAULT '',
  `keywords` varchar(300) NOT NULL DEFAULT '',
  `content` longtext NOT NULL,
  `time` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_catalog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `caption` varchar(400) NOT NULL,
  `text` mediumtext NOT NULL,
  `url` varchar(400) NOT NULL,
  `img` varchar(100) NOT NULL,
  `visible` tinyint(1) NOT NULL,
  `lang` varchar(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `nodes_catalog` (`id`, `caption`, `text`, `url`, `img`, `visible`, `lang`) VALUES
(1, 'Terms &amp; Conditions', '<ul>\r\n<li><a href="#1">Intellectual Property Rights</a></li>\r\n<li><a href="#2">Restrictions</a></li>\r\n<li><a href="#3">Your Content</a></li>\r\n<li><a href="#4">No warranties</a></li>\r\n<li><a href="#5">Limitation of liability</a></li>\r\n<li><a href="#6">Indemnification</a></li>\r\n<li><a href="#7">Severability</a></li>\r\n<li><a href="#8">Variation of Terms</a></li>\r\n<li><a href="#9">Assignment</a></li>\r\n<li><a href="#10">Entire Agreement</a></li>\r\n<li><a href="#11">Governing Law &amp; Jurisdiction</a></li>\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p>These Website Standard Terms and Conditions written on this webpage shall manage your use of this website. These Terms will be applied fully and affect to your use of this Website. By using this Website, you agreed to accept all terms and conditions written in here. You must not use this Website if you disagree with any of these Website Standard Terms and Conditions. <br /> Minors or people below 18 years old are not allowed to use this Website.</p>\r\n<p><br /> <a name="1"></a><strong>Intellectual Property Rights</strong></p>\r\n<p>Other than the content you own, under these Terms, and/or its licensors own all the intellectual property rights and materials contained in this Website. <br /> You are granted limited license only for purposes of viewing the material contained on this Website.</p>\r\n<p><br /> <a name="2"></a><strong>Restrictions</strong></p>\r\n<p>You are specifically restricted from all of the following:</p>\r\n<ul>\r\n<li>Publishing any Website material in any other media.</li>\r\n<li>Selling, sublicensing and/or otherwise commercializing any Website material.</li>\r\n<li>Publicly performing and/or showing any Website material.</li>\r\n<li>Using this Website in any way that is or may be damaging to this Website.</li>\r\n<li>Using this Website in any way that impacts user access to this Website.</li>\r\n<li>Using this Website contrary to applicable laws and regulations, or in any way may cause harm to the Website, or to any person or business entity.</li>\r\n<li>Engaging in any data mining, data harvesting, data extracting or any other similar activity in relation to this Website.</li>\r\n<li>Using this Website to engage in any advertising or marketing.</li>\r\n</ul>\r\n<p>Certain areas of this Website are restricted from being access by you and may further restrict access by you to any areas of this Website, at any time, in absolute discretion. Any user ID and password you may have for this Website are confidential and you must maintain confidentiality as well.</p>\r\n<p><br /> <a name="3"></a><strong>Your Content</strong></p>\r\n<p>In these Website Standard Terms and Conditions, &ldquo;Your Content&rdquo; shall mean any audio, video text, images or other material you choose to display on this Website. By displaying Your Content, you grant a non-exclusive, worldwide irrevocable, sub licensable license to use, reproduce, adapt, publish, translate and distribute it in any and all media. <br /> Your Content must be your own and must not be invading any third-party&rsquo;s rights. reserves the right to remove any of Your Content from this Website at any time without notice.</p>\r\n<p><br /> <a name="4"></a><strong>No warranties</strong></p>\r\n<p>This Website is provided &ldquo;as is,&rdquo; with all faults, and express no representations or warranties, of any kind related to this Website or the materials contained on this Website. Also, nothing contained on this Website shall be interpreted as advising you.</p>\r\n<p><br /> <a name="5"></a><strong>Limitation of liability</strong></p>\r\n<p>In no event shall , nor any of its officers, directors and employees, shall be held liable for anything arising out of or in any way connected with your use of this Website whether such liability is under contract. , including its officers, directors and employees shall not be held liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.</p>\r\n<p><br /> <a name="6"></a><strong>Indemnification</strong></p>\r\n<p>You hereby indemnify to the fullest extent from and against any and/or all liabilities, costs, demands, causes of action, damages and expenses arising in any way related to your breach of any of the provisions of these Terms.</p>\r\n<p><br /> <a name="7"></a><strong>Severability</strong></p>\r\n<p>If any provision of these Terms is found to be invalid under any applicable law, such provisions shall be deleted without affecting the remaining provisions herein.</p>\r\n<p><br /> <a name="8"></a><strong>Variation of Terms</strong></p>\r\n<p>is permitted to revise these Terms at any time as it sees fit, and by using this Website you are expected to review these Terms on a regular basis.</p>\r\n<p><br /> <a name="9"></a><strong>Assignment</strong></p>\r\n<p>The is allowed to assign, transfer, and subcontract its rights and/or obligations under these Terms without any notification. However, you are not allowed to assign, transfer, or subcontract any of your rights and/or obligations under these Terms.</p>\r\n<p><br /> <a name="10"></a><strong>Entire Agreement</strong></p>\r\n<p>These Terms constitute the entire agreement between and you in relation to your use of this Website, and supersede all prior agreements and understandings.</p>\r\n<p><br /> <a name="11"></a><strong>Governing Law &amp; Jurisdiction</strong></p>\r\n<p>These Terms will be governed by and interpreted in accordance with the laws of the State of , and you submit to the non-exclusive jurisdiction of the state and federal courts located in for the resolution of any disputes.</p>\r\n<p style="text-align: right;"><br /> <strong>Last Edited on 03/01/2017</strong></p>', 'terms_and_conditions', '', 0, 'en'),
(2, 'Privacy Policy', '<ul>\r\n<li><a href="#1">Information Collection</a></li>\r\n<li><a href="#2">Information Usage</a></li>\r\n<li><a href="#3">Information Protection</a></li>\r\n<li><a href="#4">Cookie Usage</a></li>\r\n<li><a href="#5">3rd Party Disclosure</a></li>\r\n<li><a href="#6">3rd Party Links</a></li>\r\n<li><a href="#7">CalOPPA</a></li>\r\n<li><a href="#8">COPPA</a></li>\r\n<li><a href="#9">Contact Information</a></li>\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p>This privacy policy has been compiled to better serve those who are concerned with how their ''Personally Identifiable Information'' (PII) is being used online. PII, as described in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.</p>\r\n<p><br /> <a name="1"></a><strong>What personal information do we collect from the people that visit our website?</strong></p>\r\n<p>When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, mailing address or other details to help you with your experience.</p>\r\n<p><br /> <strong>When do we collect information?</strong></p>\r\n<p>We collect information from you when you register on our site, place an order, subscribe to a newsletter, respond to a survey, fill out a form, Use Live Chat or enter information on our site.</p>\r\n<p><br /> <a name="2"></a><strong>How do we use your information?</strong></p>\r\n<p>We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:</p>\r\n<ul>\r\n<li>To improve our website in order to better serve you.</li>\r\n<li>To allow us to better service you in responding to your customer service requests</li>\r\n<li>To administer a contest, promotion, survey or other site feature.</li>\r\n<li>To quickly process your transactions.</li>\r\n<li>To ask for ratings and reviews of services or products.</li>\r\n<li>To follow up with them after correspondence (live chat, email or phone inquiries).</li>\r\n</ul>\r\n<p><br /> <a name="3"></a><strong>How do we protect your information?</strong></p>\r\n<p>Our site is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible. We will never ask for personal or sensitive information such as names, email addresses and credit card numbers from unauthorized users.</p>\r\n<p><br /> <a name="4"></a><strong>Do we use ''cookies''?</strong></p>\r\n<p>Yes. Cookies are small files that a site or its service provider transfers to your computer''s hard drive through your Web browser (if you allow) that enables the site''s or service provider''s systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future. We use cookies to:</p>\r\n<ul>\r\n<li>Help remember and process the items in the shopping cart.</li>\r\n<li>Understand and save user''s preferences for future visits.</li>\r\n</ul>\r\n<p>You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since browser is a little different, look at your browser''s Help Menu to learn the correct way to modify your cookies.</p>\r\n<p><br /> <strong>If users disable cookies in their browser</strong></p>\r\n<p>If you turn cookies off, some features will be disabled. Some of the features that make your site experience more efficient and may not function properly. <br /> However, you will still be able to place orders .</p>\r\n<p><br /> <a name="5"></a><strong>Third-party disclosure</strong></p>\r\n<p>We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information unless we provide users with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential. We may also release information when it''s release is appropriate to comply with the law, enforce our site policies, or protect ours or others'' rights, property or safety. <br /> However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>\r\n<p><br /> <a name="6"></a><strong>Third-party links</strong></p>\r\n<p>Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>\r\n<p><br /> <a name="7"></a><strong>California Online Privacy Protection Act</strong></p>\r\n<p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law''s reach stretches well beyond California to require any person or company in the United States (and conceivably the world) that operates websites collecting Personally Identifiable Information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared. <br /> According to CalOPPA, we agree to the following:</p>\r\n<ul>\r\n<li>Users can visit our site anonymously.</li>\r\n<li>Once this privacy policy is created, we will add a link to it on our home page or as a minimum, on the first significant page after entering our website.</li>\r\n<li>Our Privacy Policy link includes the word ''Privacy'' and can easily be found on the page specified above.</li>\r\n<li>You will be notified of any Privacy Policy changes on our Privacy Policy Page.</li>\r\n<li>Users can change your personal information by logging in to your account.</li>\r\n</ul>\r\n<p><br /> <strong>How does our site handle Do Not Track signals?</strong></p>\r\n<p>We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.</p>\r\n<p><br /> <strong>Does our site allow third-party behavioral tracking?</strong></p>\r\n<p>It''s also important to note that we allow third-party behavioral tracking</p>\r\n<p><br /> <a name="8"></a><strong>COPPA (Children Online Privacy Protection Act)</strong></p>\r\n<p>When it comes to the collection of personal information from children under the age of 13 years old, the Children''s Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, United States'' consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children''s privacy and safety online. <br /> We do not specifically market to children under the age of 13 years old.</p>\r\n<p><br /> <strong>CAN SPAM Act</strong></p>\r\n<p>The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations. <br /> To be in accordance with CANSPAM, we agree to the following: <br /> If at any time you would like to unsubscribe from receiving future emails, you can email us at and we will promptly remove you from ALL correspondence.</p>\r\n<p><br /> <a name="9"></a><strong>Contacting Us</strong></p>\r\n<p>If there are any questions regarding this privacy policy, you may contact us using the information below.</p>\r\n<p>Domain <br /> Email</p>\r\n<p style="text-align: right;"><br /><strong> Last Edited on 2016-12-30</strong></p>', 'privacy_policy', '', 0, 'en'),
(3, 'Правила и условия', '<ul>\r\n<li><a href="#1">Общие условия</a></li>\r\n<li><a href="#2">Обязательства Пользователя</a></li>\r\n<li><a href="#3">Прочие условия</a></li>\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p>Настоящее Соглашение определяет условия использования Пользователями материалов и сервисов данного вебсайта, Пользователи &mdash; физические лица (в том числе представители юридических лиц), обладающие возможностью визуального ознакомления с размещенной на сайте информацией и размещением собственной.</p>\r\n<p><br /> <a name="1"></a><strong>Общие условия</strong></p>\r\n<p>Использование материалов и сервисов Сайта регулируется нормами федерального законодательства и международными нормами. <br /> Настоящее Соглашение является публичной офертой. Получая доступ к материалам Сайта, Пользователь считается присоединившимся к настоящему Соглашению. <br /> При использовании ресурсов Сайта требующих предоставления персональных данных необходимо выполнить регистрацию Пользователя на Сайте. <br /> Администрация Сайта вправе в любое время в одностороннем порядке изменять условия настоящего Соглашения. Такие изменения вступают в силу по истечении 3 (Трех) дней с момента размещения новой версии Соглашения на сайте. При несогласии Пользователя с внесенными изменениями он обязан отказаться от доступа к Сайту, прекратить использование материалов и сервисов Сайта. <br /> Администрация Сайта может устанавливать для Пользователей рассылку информации, связанной с заказами, графиками работы офисов, проводимыми акциями и иной необходимой информацией. Рассылка осуществляется посредством сообщений sms, push или электронной почты. Необходимая контактная информация предоставляется Пользователем при регистрации.</p>\r\n<p><br /> <a name="2"></a><strong>Обязательства Пользователя</strong></p>\r\n<p>Пользователь соглашается не предпринимать действий, которые могут рассматриваться как нарушающие российское законодательство или нормы международного права, в том числе в сфере интеллектуальной собственности, авторских и/или смежных правах, а также любых действий, которые приводят или могут привести к нарушению нормальной работы Сайта и сервисов Сайта. <br /> Использование материалов Сайта без согласия правообладателей не допускается. Для правомерного использования материалов Сайта необходимо заключение лицензионных договоров (получение лицензий) от Правообладателей. <br /> При цитировании материалов Сайта, включая охраняемые авторские произведения, ссылка на Сайт обязательна. <br /> Комментарии и иные записи Пользователя на Сайте не должны вступать в противоречие с требованиями законодательства Российской Федерации и общепринятых норм морали и нравственности. <br /> Пользователь предупрежден о том, что Администрация Сайта не несет ответственности за посещение и использование им внешних ресурсов, ссылки на которые могут содержаться на сайте. <br /> Пользователь согласен с тем, что Администрация Сайта не несет ответственности и не имеет прямых или косвенных обязательств перед Пользователем в связи с любыми возможными или возникшими потерями или убытками, связанными с любым содержанием Сайта, регистрацией авторских прав и сведениями о такой регистрации, товарами или услугами, доступными на или полученными через внешние сайты или ресурсы либо иные контакты Пользователя, в которые он вступил, используя размещенную на Сайте информацию или ссылки на внешние ресурсы. <br /> Пользователь принимает положение о том, что все материалы и сервисы Сайта или любая их часть могут сопровождаться рекламой. Пользователь согласен с тем, что Администрация Сайта не несет какой-либо ответственности и не имеет каких-либо обязательств в связи с такой рекламой.</p>\r\n<p><br /> <a name="3"></a><strong>Прочие условия</strong></p>\r\n<p>Все возможные споры, вытекающие из настоящего Соглашения или связанные с ним, подлежат разрешению в соответствии с действующим законодательством Российской Федерации. <br /> Ничто в Соглашении не может пониматься как установление между Пользователем и Администрации Сайта агентских отношений, отношений товарищества, отношений по совместной деятельности, отношений личного найма, либо каких-то иных отношений, прямо не предусмотренных Соглашением. <br /> Признание судом какого-либо положения Соглашения недействительным или не подлежащим принудительному исполнению не влечет недействительности иных положений Соглашения. <br /> Бездействие со стороны Администрации Сайта в случае нарушения кем-либо из Пользователей положений Соглашения не лишает Администрацию Сайта права предпринять позднее соответствующие действия в защиту своих интересов и защиту авторских прав на охраняемые в соответствии с законодательством материалы Сайта. <br /> Пользователь подтверждает, что ознакомлен со всеми пунктами настоящего Соглашения и безусловно принимает их.</p>\r\n<p style="text-align: right;"><br /> <strong>Последнее редактирование 13/01/2017</strong></p>\r\n<p>&nbsp;</p>', 'terms_and_conditions', '', 0, 'ru'),
(4, 'Конфиденциальность', '<ul>\r\n<li><a href="#1">Сбор информации</a></li>\r\n<li><a href="#2">Использование информации</a></li>\r\n<li><a href="#3">Защита информации</a></li>\r\n<li><a href="#4">Использование cookie</a></li>\r\n<li><a href="#5">Раскрытие информации</a></li>\r\n<li><a href="#6">Сторонние ссылки</a></li>\r\n<li><a href="#7">CalOPPA</a></li>\r\n<li><a href="#8">COPPA</a></li>\r\n<li><a href="#9">Как с нами связаться</a></li>\r\n</ul>\r\n<p>&nbsp;</p>\r\n<p>Данные положения касаются персональных данных клиентов (далее &ndash; &laquo;Персональные данные&raquo;, &laquo;Личная информация&raquo;, &laquo;Личные данные&raquo;), которые могут быть идентифицированы каким-либо образом, и которые посещают веб-сайт (далее - &ldquo;Сайт&rdquo;) и пользуются его услугами (далее - &ldquo;Сервисы&rdquo;). <br /> Поправки к настоящей Политике конфиденциальности будут размещены на Сайте и/или в Сервисах и будут являться действительными сразу после публикации. Ваше дальнейшее использование Сервисов после внесения любых поправок в Политике конфиденциальности означает Ваше принятие данных изменений. <br /> Регистрируясь на Сайте, Вы подтверждаете принятие Вами решения о предоставлении своих персональных данных и даете согласие на их обработку своей волей и в своем интересе, за исключением случаев, предусмотренных законодательством.</p>\r\n<p><br /> <a name="1"></a><strong>Какую личную информацию мы собираем от людей, которые посещают наш Сайт?</strong></p>\r\n<p>Сайт собирает только личную информацию, которую Вы предоставляете добровольно при посещении или регистрации на Сайте. Понятие "личная информация" включает информацию, которая определяет Вас как конкретное лицо, например, Ваше имя или адрес электронной почты. Тогда как просматривать содержание Сайта можно без прохождения процедуры регистрации, Вам потребуется зарегистрироваться, чтобы воспользоваться некоторыми функциями, например, оставить свой комментарий к статье.</p>\r\n<p><br /> <strong>Когда мы собираем информацию?</strong></p>\r\n<p>Мы собираем информацию от вас, когда вы регистрируетесь на нашем сайте, оформиляете заказ, подписыветесь на рассылку или иным образом вводите информацию на нашем сайте.</p>\r\n<p><br /> <a name="2"></a><strong>Как мы используем вашу информацию?</strong></p>\r\n<p>Мы можем использовать информацию, которую мы получаем от вас, следующими способами:</p>\r\n<ul>\r\n<li>Для того, чтобы улучшить качество сервиса.</li>\r\n<li>Для администрирования контента и других функций сайта.</li>\r\n<li>Чтобы быстро обрабатывать ваши транзакции.</li>\r\n<li>Для того, чтобы составить рейтинги и обзоры услуг или продуктов.</li>\r\n<li>Для дальнейшего взаимодействия после переписки (чат, электронную почту или телефон).</li>\r\n</ul>\r\n<p><br /> <a name="3"></a><strong>Как мы защищаем вашу информацию?</strong></p>\r\n<p>Мы будем стремиться предотвратить несанкционированный доступ к Вашей личной информации, однако, никакая передача данных через интернет, мобильное устройство или через беспроводное устройство не могут гарантировать 100%-ную безопасность. Мы будем продолжать укреплять систему безопасности по мере доступности новых технологий и методов.</p>\r\n<p><br /> <a name="4"></a><strong>Используем ли мы ''cookies''?</strong></p>\r\n<p>Да, мы используем &ldquo;куки&rdquo; (cookies) для отслеживания информации о пользователях. Cookies являются небольшими по объему данными, которые передаются веб-сервером через Ваш веб-браузер и хранятся на жестком диске Вашего компьютера. Мы используем cookies для отслеживания вариантов страниц, которые видел посетитель, для подсчета нажатий сделанных посетителем на том или ином варианте страницы, для мониторинга трафика и для измерения популярности сервисных настроек. Мы будем использовать данную информацию, чтобы предоставить Вам релевантные данные и услуги. Данная информация также позволяет нам убедиться, что посетители видят именно ту целевую страницу, которую они ожидают увидеть, в том случае, если они возвращаются через тот же URL-адрес, и это позволяет нам сказать, сколько людей нажимает на Ваши целевые страницы.</p>\r\n<p><br /> <a name="5"></a><strong>Раскрытие информации</strong></p>\r\n<p>Мы будем раскрывать Вашу информацию третьим лицам только в соответствии с Вашими инструкциями или в случае необходимости для того, чтобы предоставить Вам определенный сервис, или по другим причинам в соответствии с действующим законодательством Российской Федерации. Мы не осуществляем, не продаем, не распространяем или раскрываем Вашу личную информацию без предварительного получения Вашего на то разрешения за исключением случаев, предусмотренных международным или федеральным законодательством.</p>\r\n<p><br /> <a name="6"></a><strong>Сторонние ссылки</strong></p>\r\n<p>Сайт может содержать ссылки на другие сайты, и мы не несем ответственности за политику конфиденциальности или содержание данных сайтов. Мы рекомендуем Вам ознакомиться с политикой конфиденциальности связанных сайтов. Их политика конфиденциальности и деятельность отличаются от наших Политики конфиденциальности и деятельности.</p>\r\n<p><br /> <a name="7"></a><strong>CalOPPA (California Online Privacy Protection Act)</strong></p>\r\n<p>Для того, чтобы отвечать требованиям CalOPPA, мы согласны на следующее:</p>\r\n<ul>\r\n<li>Пользователи могут посетить наш сайт анонимно.</li>\r\n<li>Ссылка на эту страницу размещена на главной старницы сайта.</li>\r\n<li>Вы будете уведомлены о любых изменениях политики конфиденциальности.</li>\r\n<li>Пользователи могут изменить вашу личную информацию, войдя в свой аккаунт.</li>\r\n</ul>\r\n<p><br /> <a name="8"></a><strong>COPPA (Children Online Privacy Protection Act)</strong></p>\r\n<p>Мы стремимся защищать конфиденциальность информации о детях. Наш сайт предназначен для широкой общественности, и мы не получаем преднамеренно личную информацию от детей моложе 13 лет. Когда и если на нашем сайте запрашивается информация о возрасте, и пользователи указывают возраст до 13 лет, сайт автоматически блокирует получение личной информации от таких пользователей и блокирует их регистрацию в качестве пользователей сайта.</p>\r\n<p><br /> <strong>CAN SPAM Act</strong></p>\r\n<p>Для того, чтобы отвечать требованиям CAN SPAM (Для регулирования торговли между штатами путем введения ограничений и санкций на передачу нежелательной коммерческой электронной почты через Интернет., мы согласны на следующее: <br /> Если в любое время вы хотите отказаться от получения электронных сообщений, вы можете из личного кабинета.</p>\r\n<p><br /> <a name="9"></a><strong>Как с нами связаться</strong></p>\r\n<p>Если есть какие-либо вопросы относительно политики конфиденциальности, вы можете связаться с нами, используя информацию на сайте.</p>\r\n<p style="text-align: right;"><strong>Последнее редактирование 13/01/2017</strong></p>\r\n<p>&nbsp;</p>', 'privacy_policy', '', 0, 'ru');

CREATE TABLE IF NOT EXISTS `nodes_comment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` text NOT NULL,
  `reply` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `text` text NOT NULL,
  `date` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_content` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat_id` int(11) NOT NULL,
  `url` varchar(100) NOT NULL,
  `lang` varchar(3) NOT NULL,
  `order` int(11) NOT NULL DEFAULT '0',
  `caption` varchar(400) NOT NULL,
  `text` text NOT NULL,
  `img` varchar(100) NOT NULL,
  `date` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_error` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(400) NOT NULL,
  `lang` varchar(3) NOT NULL,
  `date` int(11) NOT NULL,
  `ip` varchar(20) NOT NULL,
  `get` text NOT NULL,
  `post` text NOT NULL,
  `session` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_inbox` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from` int(11) NOT NULL,
  `to` int(11) NOT NULL,
  `text` text NOT NULL,
  `date` int(11) NOT NULL,
  `readed` int(11) NOT NULL,
  `inform` tinyint(1) NOT NULL,
  `system` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `action` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `ip` varchar(20) NOT NULL,
  `date` int(11) NOT NULL,
  `details` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_meta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(400) NOT NULL,
  `lang` varchar(4) NOT NULL,
  `title` varchar(100) NOT NULL,
  `description` varchar(200) NOT NULL,
  `keywords` varchar(300) NOT NULL,
  `mode` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `date` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `shipping` int(11) NOT NULL,
  `payment` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_outbox` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `caption` varchar(400) NOT NULL,
  `text` text NOT NULL,
  `action` tinyint(4) NOT NULL,
  `date` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_perfomance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `server_time` double NOT NULL,
  `script_time` double NOT NULL,
  `cache_id` int(11) NOT NULL,
  `date` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `text` text NOT NULL,
  `img` text NOT NULL,
  `shipping` int(11) NOT NULL,
  `price` double NOT NULL,
  `date` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `views` int(11) NOT NULL,
  `rating` int(11) NOT NULL,
  `votes` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_product_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat_id` int(11) NOT NULL,
  `value` varchar(100) NOT NULL,
  `url` varchar(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `nodes_product_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `order_id` int(11) NOT NULL,
  `price` double NOT NULL,
  `count` int(11) NOT NULL,
  `track` varchar(100) NOT NULL,
  `status` int(11) NOT NULL,
  `date` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_product_property` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat_id` int(11) NOT NULL,
  `value` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `nodes_product_property` (`id`, `cat_id`, `value`) VALUES
(1, 0, 'Category');

CREATE TABLE IF NOT EXISTS `nodes_property_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `property_id` int(11) NOT NULL,
  `data_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_referrer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_shipping` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `fname` varchar(100) NOT NULL,
  `lname` varchar(100) NOT NULL,
  `country` varchar(100) NOT NULL,
  `state` varchar(100) NOT NULL,
  `city` varchar(100) NOT NULL,
  `zip` varchar(100) NOT NULL,
  `street1` varchar(100) NOT NULL,
  `street2` varchar(100) NOT NULL,
  `phone` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_transaction` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `order_id` int(11) NOT NULL,
  `txn_id` varchar(40) NOT NULL,
  `amount` double NOT NULL,
  `status` int(11) NOT NULL,
  `date` int(11) NOT NULL,
  `payment_date` varchar(100) NOT NULL,
  `comment` text NOT NULL,
  `ip` varchar(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `nodes_user_outbox` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `outbox_id` int(11) NOT NULL,
  `date` int(11) NOT NULL,
  `status` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `nodes_agent` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `bot` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `nodes_agent` (`id`, `name`, `bot`) VALUES
(1, 'a.pr-cy.ru', 1),
(2, 'AdsBot-Google (+http://www.google.com/adsbot.html)', 1),
(3, 'AdsBot-Google-Mobile (+http://www.google.com/mobile/adsbot.html) Mozilla (iPhone; U; CPU iPhone OS 3 0 like Mac OS X) AppleWebKit (KHTML, like Gecko) Mobile Safari', 1),
(4, 'Apache-HttpClient/4.5 (Java/1.8.0_60)', 1),
(5, 'eSyndiCat Bot', 1),
(6, 'facebookexternalhit/1.1', 1),
(7, 'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)', 1),
(8, 'Google favicon', 1),
(9, 'Googlebot-Image/1.0', 1),
(10, 'GuzzleHttp/6.1.0 curl/7.26.0 PHP/5.5.29-1~dotdeb+7.1', 1),
(11, 'GuzzleHttp/6.1.0 curl/7.35.0 PHP/5.6.14-1+deb.sury.org~trusty+1', 1),
(12, 'Java/1.4.1_04', 1),
(13, 'Java/1.8.0_60', 1),
(14, 'LinksMasterRoBot/0.01 (http://www.linksmaster.ru)', 1),
(15, 'LinkStats Bot', 1),
(16, 'ltx71 - (http://ltx71.com/)', 1),
(17, 'Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ahrefs.com/robot/)', 1),
(18, 'Mozilla/5.0 (compatible; archive.org_bot; Wayback Machine Live Record; +http://archive.org/details/archive.org_bot)', 1),
(19, 'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)', 1),
(20, 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)', 1),
(21, 'Mozilla/5.0 (compatible; CNCat/4.2; +http://www.cn-software.com/en/cncat/robot/)', 1),
(22, 'Mozilla/5.0 (compatible; CNCat/4.2; +http://www.vipwords.com/en/cncat/robot/)', 1),
(23, 'Mozilla/5.0 (compatible; DeuSu/5.0.2; +https://deusu.de/robot.html)', 1),
(24, 'Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)', 1),
(25, 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', 1),
(26, 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)/1.8 (InfoSeek crawler; http://www.infoseek.com; crawler@infoseek.com)', 1),
(27, 'Mozilla/5.0 (compatible; Google-Site-Verification/1.0)', 1),
(28, 'Mozilla/5.0 (compatible; GrapeshotCrawler/2.0; +http://www.grapeshot.co.uk/crawler.php)', 1),
(29, 'Mozilla/5.0 (compatible; linkdexbot/2.2; +http://www.linkdex.com/bots/)', 1),
(30, 'Mozilla/5.0 (compatible; LinkpadBot/1.06; +http://www.linkpad.ru)', 1),
(31, 'Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/2.0; +http://go.mail.ru/help/robots)', 1),
(32, 'Mozilla/5.0 (compatible; Linux x86_64; Mail.RU_Bot/Fast/2.0; +http://go.mail.ru/help/robots)', 1),
(33, 'Mozilla/5.0 (compatible; meanpathbot/1.0; +http://www.meanpath.com/meanpathbot.html)', 1),
(34, 'Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)', 1),
(35, 'Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)', 1),
(36, 'Mozilla/5.0 (compatible; NetSeer crawler/2.0; +http://www.netseer.com/crawler.html; crawler@netseer.com)', 1),
(37, 'Mozilla/5.0 (compatible; openstat.ru/Bot)', 1),
(38, 'Mozilla/5.0 (compatible; SemrushBot/0.99~bl; +http://www.semrush.com/bot.html)', 1),
(39, 'Mozilla/5.0 (compatible; SputnikFaviconBot/1.2; +http://corp.sputnik.ru/webmaster)', 1),
(40, 'Mozilla/5.0 (compatible; statdom.ru/Bot; +http://statdom.ru/bot.html)', 1),
(41, 'Mozilla/5.0 (compatible; StatOnlineRuBot/1.0)', 1),
(42, 'Mozilla/5.0 (compatible; vkShare; +http://vk.com/dev/Share)', 1),
(43, 'Mozilla/5.0 (compatible; WebArtexBot; +http://webartex.ru/)', 1),
(44, 'Mozilla/5.0 (compatible; Web-Monitoring/1.0; +http://monoid.nic.ru/)', 1),
(45, 'Mozilla/5.0 (compatible; YaDirectFetcher/1.0; +http://yandex.com/bots)', 1),
(46, 'Mozilla/5.0 (compatible; YaDirectFetcher/1.0; Dyatel; +http://yandex.com/bots)', 1),
(47, 'Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)', 1),
(48, 'Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)', 1),
(49, 'Mozilla/5.0 (compatible; YandexDirect/3.0; +http://yandex.com/bots)', 1),
(50, 'Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)', 1),
(51, 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots DEV)', 1),
(52, 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01e.yandex.ru)', 1),
(53, 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01g.yandex.ru)', 1),
(54, 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtmon01i.yandex.ru)', 1),
(55, 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots mtweb01t.yandex.ru)', 1),
(56, 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots)', 1),
(57, 'Mozilla/5.0 (compatible; YandexMetrika/3.0; +http://yandex.com/bots)', 1),
(58, 'Mozilla/5.0 (compatible; YandexWebmaster/2.0; +http://yandex.com/bots)', 1),
(59, 'Mozilla/5.0 (compatible; YandexWebmaster/2.0; +http://yandex.com/bots)', 1),
(60, 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B411 Safari/600.1.4 (compatible; YandexMobileBot/3.0; +http://yandex.com/bots)', 1),
(61, 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', 1),
(62, 'Mozilla/5.0 (Windows NT 6.2; WOW64) Runet-Research-Crawler (itrack.ru/research/cmsrate; rating@itrack.ru)', 1),
(63, 'Mozilla/5.0 (Windows NT 6.2; WOW64) Runet-Research-Crawler (itrack.ru/research/cmsrate; rating@itrack.ru)', 1),
(64, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en; rv:1.9.0.13) Gecko/2009073022 Firefox/3.5.2 (.NET CLR 3.5.30729) SurveyBot/2.3 (DomainTools)', 1),
(65, 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-GB; rv:1.0; trendictionbot0.5.0; trendiction search; http://www.trendiction.de/bot; please let us know of any problems; web at trendiction.com) Gecko/20071127 Firefox/3.0.0.11', 1),
(66, 'Netcat Bot', 1),
(67, 'netEstate NE Crawler (+http://www.website-datenbank.de/)', 1),
(68, 'OdklBot/1.0 (klass@odnoklassniki.ru)', 1),
(69, 'parser3', 1),
(70, 'PEAR HTTP_Request class ( http://pear.php.net/ )', 1),
(71, 'pr-cy.ru Screenshot Bot', 1),
(72, 'python-requests/2.8.1', 1),
(73, 'Riddler (http://riddler.io/about)', 1),
(74, 'rogerbot/1.0 (http://moz.com/help/pro/what-is-rogerbot-, rogerbot-wherecat@moz.com)', 1),
(75, 'RookeeBot', 1),
(76, 'SafeDNS search bot/Nutch-1.9 (https://www.safedns.com/searchbot; support [at] safedns [dot] com)', 1),
(77, 'SeopultContentAnalyzer/1.0', 1),
(78, 'Validator.nu/LV http://validator.w3.org/services', 1),
(79, 'W3C_Validator/1.3 http://validator.w3.org/services', 1),
(80, 'W3C_Validator/1.3 libwww-perl/6.05', 1),
(81, 'Websquash.com (Add url robot)', 1),
(82, 'Who.is Bot', 1),
(83, 'Y!J-ASR/0.1 crawler (http://www.yahoo-help.jp/app/answers/detail/p/595/a_id/42716/)', 1),
(84, 'Yandex/1.01.001 (compatible; Win16; I)', 1),
(85, 'Nodes Studio', 1),
(86, 'Nodes Studio 2.0', 1),
(88, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393', 0),
(89, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36', 0);

CREATE TABLE IF NOT EXISTS `nodes_language` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `lang` varchar(3) NOT NULL,
  `value` text NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `nodes_language` (`name`, `lang`, `value`) VALUES
('Upload', 'en', 'Upload'),
('Link', 'en', 'Link'),
('Cancel', 'en', 'Cancel'),
('Uploaded', 'en', 'Uploaded'),
('For uploading selected area use double click', 'en', 'For uploading selected area use double click'),
('Error', 'en', 'Error'),
('Or file', 'en', 'Or file'),
('Upload image', 'en', 'Upload image'),
('Received', 'ru', 'Получено'),
('Sitemap', 'en', 'Sitemap'),
('Format', 'en', 'Format'),
('Upload new image', 'en', 'Upload new image'),
('Logout sucsessful', 'en', 'Logout sucsessful'),
('Quit', 'en', 'Quit'),
('Site', 'en', 'Site'),
('Users', 'en', 'Users'),
('Comments', 'en', 'Comments'),
('Content', 'en', 'Content'),
('Errors', 'en', 'Errors'),
('Files', 'en', 'Files'),
('Images', 'en', 'Images'),
('Videos', 'en', 'Videos'),
('Access', 'en', 'Access'),
('Config', 'en', 'Config'),
('Backend', 'en', 'Backend'),
('Logout', 'en', 'Logout'),
('new messages', 'ru', 'новые сообщения'),
('Password', 'en', 'Password'),
('Upload selection as thumb?', 'en', 'Upload selection as thumb?'),
('Save uploaded images', 'en', 'Save uploaded images'),
('Previous page', 'en', 'Previous page'),
('Next page', 'en', 'Next page'),
('Updated', 'en', 'Updated'),
('Interval', 'en', 'Interval'),
('Not existing', 'en', 'Not existing'),
('Not cathing', 'en', 'Not cathing'),
('Not refreshing', 'en', 'Not refreshing'),
('minut', 'en', 'minut'),
('minuts', 'en', 'minuts'),
('hour', 'en', 'hour'),
('hours', 'en', 'hours'),
('Dayly', 'en', 'Dayly'),
('Change interval', 'en', 'Change interval'),
('Refresh catch', 'en', 'Refresh catch'),
('Edit article', 'en', 'Edit article'),
('Caption', 'en', 'Caption'),
('No image', 'en', 'No image'),
('Edit directory', 'en', 'Edit directory'),
('Return', 'en', 'Return'),
('Add new article', 'en', 'Add new article'),
('Edit', 'en', 'Edit'),
('Delete', 'en', 'Delete'),
('Add a new directory', 'en', 'Add a new directory'),
('Description', 'en', 'Description'),
('Back', 'en', 'Back'),
('List', 'en', 'List'),
('Add', 'en', 'Add'),
('Preview', 'en', 'Preview'),
('Uploading files', 'en', 'Uploading files'),
('File', 'en', 'File'),
('Submit', 'en', 'Submit'),
('Included files', 'en', 'Included files'),
('Path', 'en', 'Path'),
('Class', 'en', 'Class'),
('Create new file', 'en', 'Create new file'),
('Lost password', 'en', 'Lost password'),
('allready exist', 'en', 'already exist'),
('Incorrect email of password', 'en', 'Incorrect email of password'),
('not found', 'en', 'not found'),
('Message with new password is sended to email', 'en', 'Message with new password is sended to email'),
('New password is', 'en', 'New password is'),
('New password for', 'en', 'New password for'),
('Registration sucsessful', 'en', 'Registration successful'),
('We are glad to confirm sucsessful registration at', 'en', 'We are glad to confirm successful registration at'),
('About software', 'en', 'About software'),
('Errors not found', 'en', 'Errors not found'),
('Clear log', 'en', 'Clear log'),
('Date', 'en', 'Date'),
('New user', 'en', 'New user'),
('Name', 'en', 'Name'),
('Ban', 'en', 'Ban'),
('Unban', 'en', 'Unban'),
('Confirm deleting banned user', 'en', 'Confirm deleting banned user'),
('Create user', 'en', 'Create user'),
('Incorrect email', 'en', 'Incorrect email'),
('Enter password', 'en', 'Enter password'),
('Update interval', 'en', 'Update interval'),
('All pages', 'en', 'All pages'),
('Logs', 'en', 'Logs'),
('Text', 'en', 'Text'),
('Pages not found', 'en', 'Pages not found'),
('Sign Up', 'en', 'Sign Up'),
('Admin', 'en', 'Admin'),
('Upload files', 'en', 'Upload files'),
('Account', 'en', 'Account'),
('Save settings', 'en', 'Save settings'),
('Access denied', 'en', 'Access denied'),
('Message sent successfully', 'en', 'Message sent successfully'),
('New message from', 'en', 'New message from'),
('My Account', 'en', 'My Account'),
('Show navigation', 'en', 'Show navigation'),
('Get in Touch', 'en', 'Get in Touch'),
('Contact Us', 'en', 'Contact Us'),
('Your message here', 'en', 'Your message here'),
('Send message', 'en', 'Send message'),
('Developed by', 'en', 'Developed by'),
('Up', 'en', 'Up'),
('Show All', 'en', 'Show All'),
('Change picture', 'en', 'Change picture'),
('Enter your email and password to continue', 'en', 'Enter your email and password to continue'),
('Settings', 'en', 'Settings'),
('Email', 'en', 'Email'),
('New password', 'en', 'New password'),
('Enter your email', 'en', 'Enter your email'),
('Enter your password', 'en', 'Enter your password'),
('Save changes', 'en', 'Save changes'),
('Back to account', 'en', 'Back to account'),
('Invalid conformation code', 'en', 'Invalid conformation code'),
('Registration at', 'en', 'Registration at'),
('Confirmation code', 'en', 'Confirmation code'),
('No articles found', 'en', 'No articles found'),
('Messages', 'en', 'Messages'),
('Back to admin', 'en', 'Back to admin'),
('Status', 'en', 'Status'),
('Yes', 'en', 'Yes'),
('No', 'en', 'No'),
('Show in navigation', 'en', 'Show in navigation'),
('Back to content', 'en', 'Back to content'),
('Delete image', 'en', 'Delete image'),
('Comments not found', 'en', 'Comments not found'),
('Add reply', 'en', 'Add reply'),
('Users not found', 'en', 'Users not found'),
('Share friends in', 'en', 'Share friends in'),
('Language', 'en', 'Language'),
('Home', 'en', 'Home'),
('Connect us at', 'en', 'Connect us at'),
('Copyright', 'en', 'Copyright'),
('All rights reserved', 'en', 'All rights reserved'),
('There is no users, you can send a message', 'en', 'There is no users, you can send a message'),
('offline', 'en', 'offline'),
('Add comment', 'en', 'Add comment'),
('Submit comment', 'en', 'Submit comment'),
('Add new comment', 'en', 'Add new comment'),
('There is no comments', 'en', 'There is no comments'),
('Comment submited!', 'en', 'Comment submited!'),
('To post a comment, please', 'en', 'To post a comment, please'),
('Updating engine from version', 'ru', 'Обновления движка с версии'),
('Reply', 'en', 'Reply'),
('Upload', 'ru', 'Загрузить'),
('Link', 'ru', 'Ссылка'),
('Cancel', 'ru', 'Отмена'),
('Uploaded', 'ru', 'Загружено'),
('For uploading selected area use double click', 'ru', 'Для сохранения выделенной области используй двойной клик'),
('Error', 'ru', 'Ошибка'),
('Upload image', 'ru', 'Загрузить изображение'),
('Sitemap', 'ru', 'Карта сайта'),
('Format', 'ru', 'Маска'),
('Upload new image', 'ru', 'Загрузить новое изобр.'),
('Logout sucsessful', 'ru', 'Сессия завершена'),
('Quit', 'ru', 'Выход'),
('Site', 'ru', 'Сайт'),
('Users', 'ru', 'Пользователи'),
('Comments', 'ru', 'Комментарии'),
('Content', 'ru', 'Контент'),
('Errors', 'ru', 'Ошибки'),
('Files', 'ru', 'Файлы'),
('Images', 'ru', 'Изображения'),
('Videos', 'ru', 'Видео'),
('Access', 'ru', 'Доступ'),
('Config', 'ru', 'Настройки'),
('Backend', 'ru', 'Бекенд'),
('Logout', 'ru', 'Выход'),
('Authentication timeout', 'ru', 'Таймаут аутенфикации'),
('Password', 'ru', 'Пароль'),
('Upload selection as thumb?', 'ru', 'Загрузить выделенную облать как превью?'),
('Save uploaded images', 'ru', 'Сохранить загруженные'),
('Previous page', 'ru', 'Предыдущая страница'),
('Next page', 'ru', 'Следующая страница'),
('Updated', 'ru', 'Обновлено'),
('Interval', 'ru', 'Интервал'),
('Not existing', 'ru', 'Не существует'),
('Not cathing', 'ru', 'Не кешируется'),
('Not refreshing', 'ru', 'Не обновляется'),
('minut', 'ru', 'минут'),
('minuts', 'ru', 'минут'),
('hour', 'ru', 'час'),
('hours', 'ru', 'часов'),
('Dayly', 'ru', 'Суточно'),
('Change interval', 'ru', 'Изменить интервал'),
('Refresh catch', 'ru', 'Обновить кэш'),
('Edit article', 'ru', 'Редактировать статью'),
('Caption', 'ru', 'Название'),
('No image', 'ru', 'Нет изображения'),
('Edit directory', 'ru', 'Редактировать раздел'),
('Return', 'ru', 'Назад'),
('Add new article', 'ru', 'Добавить новую статью'),
('Edit', 'ru', 'Редактировать'),
('Delete', 'ru', 'Удалить'),
('Add a new directory', 'ru', 'Добавить раздел'),
('Description', 'ru', 'Описание'),
('Back', 'ru', 'Назад'),
('List', 'ru', 'Список'),
('Add', 'ru', 'Добавить'),
('Preview', 'ru', 'Превью'),
('Uploading files', 'ru', 'Загрузка файлов'),
('File', 'ru', 'Файл'),
('Submit', 'ru', 'Отправить'),
('Included files', 'ru', 'Подключенные файлы'),
('Path', 'ru', 'Путь'),
('Class', 'ru', 'Класс'),
('Create new file', 'ru', 'Создать новый файл'),
('Lost password', 'ru', 'Забыли пароль'),
('allready exist', 'ru', 'уже существует'),
('Incorrect email of password', 'ru', 'Неправильный email или пароль'),
('not found', 'ru', 'не найден'),
('Message with new password is sended to email', 'ru', 'Письмо с новым паролем отправлено на указанный email'),
('New password is', 'ru', 'Новый пароль'),
('New password for', 'ru', 'Новый пароль для'),
('Registration sucsessful', 'ru', 'Вы успешно зарегистрировались'),
('We are glad to confirm sucsessful registration at', 'ru', 'Мы рады сообщить, что Вы успешно зарегистрировались на'),
('About software', 'ru', 'О программе'),
('Errors not found', 'ru', 'Ошибок не найдено'),
('Clear log', 'ru', 'Очистить список'),
('Date', 'ru', 'Дата'),
('New user', 'ru', 'Новый пользователь'),
('Name', 'ru', 'Имя'),
('Ban', 'ru', 'Забанить'),
('Unban', 'ru', 'Разбанить'),
('Confirm deleting banned user', 'ru', 'Удалить забаненного пользователя, без возможности восстановления'),
('Create user', 'ru', 'Создать пользователя'),
('Incorrect email', 'ru', 'Неправильный email'),
('Enter password', 'ru', 'Введите пароль'),
('Update interval', 'ru', 'Обновить интервал'),
('All pages', 'ru', 'Все страницы'),
('Logs', 'ru', 'Логи'),
('Text', 'ru', 'Текст'),
('Pages not found', 'ru', 'Страниц не найдено'),
('Sign Up', 'ru', 'Регистрация'),
('Admin', 'ru', 'Админ'),
('Upload files', 'ru', 'Загрузка файлов'),
('Account', 'ru', 'Аккаунт'),
('Save settings', 'ru', 'Сохранить настройки'),
('Access denied', 'ru', 'Доступ запрещен'),
('Message sent successfully', 'ru', 'Сообщение успешно отправлено'),
('New message from', 'ru', 'Новое сообщение от'),
('My Account', 'ru', 'Мой аккаунт'),
('Show navigation', 'ru', 'Показать навигацию'),
('Your message here', 'ru', 'Ваше сообщение'),
('Send message', 'ru', 'Отправить сообщение'),
('Developed by', 'ru', 'Разработано на базе'),
('Up', 'ru', 'Вверх'),
('Show All', 'ru', 'Показать все'),
('Change picture', 'ru', 'Сменить изображение'),
('Enter your email and password to continue', 'ru', 'Для продолжения укажите ваш email и пароль'),
('Settings', 'ru', 'Настройки'),
('Email', 'ru', 'Email'),
('New password', 'ru', 'Новый пароль'),
('Enter your email', 'ru', 'Укажите ваш email'),
('Enter your password', 'ru', 'Укажите ваш пароль'),
('Save changes', 'ru', 'Сохранить настройки'),
('Back to account', 'ru', 'Назад в аккаунт'),
('Invalid conformation code', 'ru', 'Неправильный код подтверждения'),
('Registration at', 'ru', 'Регистрация на'),
('Confirmation code', 'ru', 'Код подтверждения'),
('No articles found', 'ru', 'Статей не найдено'),
('Messages', 'ru', 'Сообщения'),
('Back to admin', 'ru', 'Назад в админку'),
('Status', 'ru', 'Статус'),
('Yes', 'ru', 'Да'),
('No', 'ru', 'Нет'),
('Show in navigation', 'ru', 'Показать в навигации'),
('Back to content', 'ru', 'Назад к содержанию'),
('Delete image', 'ru', 'Удалить изображение'),
('Comments not found', 'ru', 'Комментариев не найдено'),
('Add reply', 'ru', 'Добавить ответ'),
('Users not found', 'ru', 'Пользователей не найдено'),
('Share friends in', 'ru', 'Рассказать друзьям в'),
('Language', 'ru', 'Язык'),
('Home', 'ru', 'Главная'),
('Connect us at', 'ru', 'Связаться в '),
('All rights reserved', 'ru', 'Все права защищены'),
('There is no users, you can send a message', 'ru', 'Контакты отсутствуют'),
('Add comment', 'ru', 'Добавить комментарий'),
('Submit comment', 'ru', 'Отправить комментарий'),
('Add new comment', 'ru', 'Добавить новый комментарий'),
('There is no comments', 'ru', 'Комментарии отсутствуют'),
('Comment submited!', 'ru', 'Комментарий отправлен!'),
('To post a comment, please', 'ru', 'Чтобы отправить комментарий, '),
('Restore password', 'ru', 'Восстановить пароль'),
('Reply', 'ru', 'Ответ'),
('Enabled', 'ru', 'Включено'),
('Autoupdate', 'ru', 'Автообновление'),
('Authentication error', 'ru', 'Ошибка аутенфикации'),
('Disabled', 'ru', 'Отключено'),
('Select your language', 'en', 'Select your language'),
('Select your language', 'ru', 'Выбирете язык'),
('Search', 'en', 'Search'),
('Search results by request', 'en', 'Search results by request'),
('Documentation', 'en', 'Documentation'),
('Add new value', 'en', 'Add new value'),
('Or file', 'ru', 'Или файл'),
('Online', 'ru', 'онлайн'),
('Get in Touch', 'ru', 'Связаться'),
('Contact Us', 'ru', 'Напишите нам'),
('Copyright', 'ru', 'Copyright'),
('offline', 'ru', 'оффлайн'),
('Search', 'ru', 'Поиск'),
('Search results by request', 'ru', 'Поиск по запросу'),
('Documentation', 'ru', 'Документация'),
('Add new value', 'ru', 'Добавить запись'),
('Download', 'en', 'Download'),
('Install', 'en', 'Install'),
('Framework', 'en', 'Framework'),
('auth', 'ru', 'Авторизуйтесь'),
('Useful services', 'en', 'Useful services'),
('Setup', 'en', 'Setup'),
('Login to send message', 'en', 'Login to send message'),
('Add article', 'en', 'Add article'),
('Download', 'ru', 'Скачать'),
('Install', 'ru', 'Установить'),
('Framework', 'ru', 'Структура'),
('Useful services', 'ru', 'Полезные сервисы'),
('Setup', 'ru', 'Установка'),
('Login to send message', 'ru', 'Авторизуйтесь, чтобы отправить сообщение'),
('Add article', 'ru', 'Добавить статью'),
('register now', 'ru', 'Зарегистрируйтесь'),
('register now', 'en', 'register now'),
('auth', 'en', 'auth'),
('There is no articles', 'en', 'There is no articles'),
('Functions', 'en', 'Functions'),
('Database', 'en', 'Database'),
('There is no articles', 'ru', 'Статей не найдено'),
('Functions', 'ru', 'Функции'),
('Database', 'ru', 'База данных'),
('Clear logs', 'ru', 'Очистить логи'),
('Logs not found', 'ru', 'Логи не найдены'),
('Sorry, no results found', 'en', 'Sorry, no results found'),
('Search results for', 'ru', 'Результаты поиска'),
('Sorry, no results found', 'ru', 'По вашему запросу ничего не нашлось'),
('Value', 'en', 'Value'),
('Showing', 'en', 'Showing'),
('to', 'en', 'to'),
('from', 'en', 'from'),
('entries', 'en', 'entries'),
('per page', 'en', 'per page'),
('Next', 'en', 'Next'),
('IP', 'ru', ''),
('New message', 'ru', 'Новое сообщение'),
('Previous', 'en', 'Previous'),
('Code', 'en', 'Code'),
('Select option', 'en', 'Select option'),
('Content not found', 'en', 'Content not found'),
('Crop image', 'en', 'Crop image'),
('Value', 'ru', 'Значение'),
('Showing', 'ru', 'Отображаются'),
('to', 'ru', 'по'),
('from', 'ru', 'из'),
('entries', 'ru', 'вхождений'),
('per page', 'ru', 'на страницу'),
('Next', 'ru', 'Вперед'),
('Account confirmation', 'ru', 'Подтверждение аккаунта'),
('Previous', 'ru', 'Назад'),
('Code', 'ru', 'Код'),
('Select option', 'ru', 'Выберете опцию'),
('Content not found', 'ru', 'Данных не найдено'),
('Crop image', 'ru', 'Обрезать изображение'),
('Sended', 'en', 'Sended'),
('at', 'en', 'at'),
('Sended', 'ru', 'Отправлено'),
('at', 'ru', 'в'),
('Too many failed attempts', 'en', 'Too many failed attempts'),
('Try again after', 'en', 'Try again after'),
('seconds', 'en', 'seconds'),
('Action', 'en', 'Action'),
('User', 'en', 'User'),
('IP', 'en', 'IP'),
('Too many failed attempts', 'ru', 'Слишком много неудачных попыток'),
('User', 'ru', 'Пользователь'),
('Action', 'ru', 'Действие'),
('seconds', 'ru', 'секунд'),
('Try again after', 'ru', 'Попробуйте еще через'),
('New message', 'en', 'New message'),
('Clear logs', 'en', 'Clear logs'),
('Logs not found', 'en', 'Logs not found'),
('Updates', 'en', 'Updates'),
('Autoupdate', 'en', 'Autoupdate'),
('Enabled', 'en', 'Enabled'),
('Disabled', 'en', 'Disabled'),
('Authentication error', 'en', 'Authentication error'),
('Authentication timeout', 'en', 'Authentication timeout'),
('Restore password', 'en', 'Restore password'),
('Received', 'en', 'Received'),
('new messages', 'en', 'new messages'),
('Updating engine from version', 'en', 'Updating engine from version'),
('Downloading files', 'en', 'Downloading files'),
('Receiving', 'en', 'Receiving'),
('Update aborted', 'en', 'Update aborted'),
('Replacing downloaded files from', 'en', 'Replacing downloaded files from'),
('Receiving MySQL data', 'en', 'Receiving MySQL data'),
('Executed', 'en', 'Executed'),
('commands', 'en', 'commands'),
('Updating to version', 'en', 'Updating to version'),
('is complete', 'en', 'is complete'),
('after 5 seconds', 'en', 'after 5 seconds'),
('Current version', 'en', 'Current version'),
('New updates available', 'en', 'New updates available'),
('Update Now', 'en', 'Update Now'),
('No updates available', 'en', 'No updates available'),
('Invalid confirmation code', 'en', 'Invalid confirmation code'),
('Data not found', 'en', 'Data not found'),
('Trying to register', 'en', 'Trying to register'),
('Comment posted', 'en', 'Comment posted'),
('There is no files', 'en', 'There is no files'),
('Downloading files', 'ru', 'Скачивание файлов'),
('Receiving', 'ru', 'Получение'),
('Update aborted', 'ru', 'Обновление прекращено'),
('Replacing downloaded files from', 'ru', 'Перемещение скачанных файлов из'),
('Receiving MySQL data', 'ru', 'Получение MySQL данных'),
('Executed', 'ru', 'Исполнено'),
('commands', 'ru', 'комманд'),
('Updating to version', 'ru', 'Обновление до версии'),
('is complete', 'ru', 'завершено'),
('after 5 seconds', 'ru', 'через 5 секунд'),
('Current version', 'ru', 'Текущая версия'),
('New updates available', 'ru', 'Доступно обновление'),
('Update Now', 'ru', 'Обновить сейчас'),
('No updates available', 'ru', 'Обновление недоступно'),
('Invalid confirmation code', 'ru', 'Неверный код подтверждения'),
('Data not found', 'ru', 'Данные не найдены'),
('Trying to register', 'ru', 'Попытка регистрации'),
('Comment posted', 'ru', 'Добавлен комментарий'),
('There is no files', 'ru', 'Файлов не найдено'),
('Updates', 'ru', 'Обновления'),
('Login', 'en', 'Login'),
('Loading', 'en', 'Loading'),
('Page not found', 'en', 'Page not found'),
('Back to Home Page', 'en', 'Back to Home Page'),
('or', 'en', 'or'),
('Login', 'ru', 'Логин'),
('Attendance', 'en', 'Attendance'),
('Page not found', 'ru', 'Страница не найдена'),
('Back to Home Page', 'ru', 'Назад на главную'),
('or', 'ru', 'или'),
('Loading', 'ru', 'Загрузка'),
('Back to Top', 'en', 'Back to Top'),
('Search results for', 'en', 'Search results for'),
('Templates', 'en', 'Templates'),
('Default file', 'en', 'Default file'),
('New file', 'en', 'New file'),
('New template', 'en', 'New template'),
('Default template', 'en', 'Default template'),
('Template name', 'en', 'Template name'),
('Views', 'en', 'Views'),
('Visitors', 'en', 'Visitors'),
('Statistic', 'en', 'Statistic'),
('Pages', 'en', 'Pages'),
('Referrers', 'en', 'Referrers'),
('By days', 'en', 'By days'),
('By weeks', 'en', 'By weeks'),
('By months', 'en', 'By months'),
('Amount', 'en', 'Amount'),
('Blank', 'en', 'Blank'),
('Restore your password', 'en', 'Restore your password'),
('To restore your password, use this code', 'en', 'To restore your password, use this code'),
('Message with confirmation code is sended to email', 'en', 'Message with confirmation code is sended to email'),
('There is no templates', 'en', 'There is no templates'),
('Register', 'en', 'Register'),
('Try to register', 'en', 'Try to register'),
('Trying to login', 'en', 'Trying to login'),
('Engine update', 'en', 'Engine update'),
('Attendance', 'ru', 'Посещаемость'),
('Back to Top', 'ru', 'Наверх'),
('Templates', 'ru', 'Шаблоны'),
('Default file', 'ru', 'Файл по-умолчанию'),
('New file', 'ru', 'Новый файл'),
('New template', 'ru', 'Новый шаблон'),
('Default template', 'ru', 'Шаблон по-умолчанию'),
('Template name', 'ru', 'Название шаблона'),
('Views', 'ru', 'Просмотры'),
('Visitors', 'ru', 'Посетители'),
('Statistic', 'ru', 'Статистика'),
('Pages', 'ru', 'Страницы'),
('Referrers', 'ru', 'Источники'),
('By days', 'ru', 'По дням'),
('By weeks', 'ru', 'По неделям'),
('By months', 'ru', 'По месяцам'),
('Amount', 'ru', 'Количество'),
('Blank', 'ru', 'Пусто'),
('Restore your password', 'ru', 'Восстановить пароль'),
('To restore your password, use this code', 'ru', 'Для восстановления пароля используйте этот код'),
('Message with confirmation code is sended to email', 'ru', 'Письмо с кодом подтверждения отправлено на указаный email'),
('There is no templates', 'ru', 'Шаблоны отсутствуют'),
('Register', 'ru', 'Регистрация'),
('Try to register', 'ru', 'Попытка регистрации'),
('Trying to login', 'ru', 'Попытка авторизации'),
('Engine update', 'ru', 'Обновление движка'),
('Withdrawal already requested', 'en', 'Withdrawal already requested'),
('Withdrawal request accepted', 'en', 'Withdrawal request accepted'),
('Select file', 'en', 'Select file'),
('Editable file', 'en', 'Editable file'),
('Source file', 'en', 'Source file'),
('Gateway Timeout', 'en', 'Gateway Timeout'),
('Image too small. Minimal size is 400x400', 'en', 'Image too small. Minimal size is 400x400'),
('Drop files here', 'en', 'Drop files here'),
('System message', 'en', 'System message'),
('sign in', 'en', 'sign in'),
('Confirm Shipment', 'en', 'Confirm Shipment'),
('Post track number', 'en', 'Post track number'),
('Shipment is confirmed', 'en', 'Shipment is confirmed'),
('This item is sold out now?', 'en', 'This item is sold out now?'),
('New order', 'en', 'New order'),
('Archive order', 'en', 'Archive order'),
('Finished', 'en', 'Finished'),
('Purchaser', 'en', 'Purchaser'),
('Shipping address', 'en', 'Shipping address'),
('All Items', 'en', 'All Items'),
('Buy Now!', 'en', 'Buy Now!'),
('Title', 'en', 'Title'),
('Ask price', 'en', 'Ask price'),
('Edit product', 'en', 'Edit product'),
('Click to Deactivate', 'en', 'Click to Deactivate'),
('Click to Activate', 'en', 'Click to Activate'),
('You might also be interested in', 'en', 'You might also be interested in'),
('Products not found', 'en', 'Products not found'),
('Category', 'en', 'Category'),
('Reset Filter', 'en', 'Reset Filter'),
('Unable to purchase your own product', 'en', 'Unable to purchase your own product'),
('Buy Now', 'en', 'Buy Now'),
('Tracking number', 'en', 'Tracking number'),
('Shipment in process', 'en', 'Shipment in process'),
('Confirm receipt', 'en', 'Confirm receipt'),
('Seller', 'en', 'Seller'),
('Shipping from', 'en', 'Shipping from'),
('Category', 'ru', 'Категория'),
('Reset Filter', 'ru', 'Сбросить'),
('Unable to purchase your own product', 'ru', 'Нельзя приобрести свой товар'),
('New comment at', 'en', 'New comment at'),
('You might also be interested in', 'ru', 'Вас может заинтересовать'),
('Products not found', 'ru', 'Товары не найдены'),
('New message at', 'en', 'New message at'),
('Dear', 'en', 'Dear'),
('sent a message for you', 'en', 'sent a message for you'),
('For details, click', 'en', 'For details, click'),
('here', 'en', 'here'),
('Withdrawal request at', 'en', 'Withdrawal request at'),
('You withdrawal request is pending now', 'en', 'You withdrawal request is pending now'),
('After some time you will receive', 'en', 'After some time you will receive'),
('on your PayPal account', 'en', 'on your PayPal account'),
('There in new withdrawal request at', 'en', 'There in new withdrawal request at'),
('Need to pay', 'en', 'Need to pay'),
('on PayPal account', 'en', 'on PayPal account'),
('and confirm request', 'en', 'and confirm request'),
('Details', 'en', 'Details'),
('Withdrawal is complete at', 'en', 'Withdrawal is complete at'),
('You withdrawal is complete', 'en', 'You withdrawal is complete'),
('Thanks for using our service and have a nice day', 'en', 'Thanks for using our service and have a nice day'),
('New purchase at', 'en', 'New purchase at'),
('Congratulations on your purchase at', 'en', 'Congratulations on your purchase at'),
('You can see details of your purchases', 'en', 'You can see details of your purchases'),
('There in new purchase at', 'en', 'There in new purchase at'),
('make a payment', 'en', 'make a payment'),
('to your PayPal account', 'en', 'to your PayPal account'),
('Your order has been shipped at', 'en', 'Your order has been shipped at'),
('Your order', 'en', 'Your order'),
('has been shipped', 'en', 'has been shipped'),
('After receiving, please update purchase status', 'en', 'After receiving, please update purchase status'),
('Your order has been completed at', 'en', 'Your order has been completed at'),
('Your order has been completed', 'en', 'Your order has been completed'),
('Funds added to your account and available for withdrawal', 'en', 'Funds added to your account and available for withdrawal'),
('Orders not found', 'en', 'Orders not found'),
('Type', 'en', 'Type'),
('Withdrawal request', 'en', 'Withdrawal request'),
('Money deposit', 'en', 'Money deposit'),
('Order', 'en', 'Order'),
('Please, confirm transaction', 'en', 'Please, confirm transaction'),
('Confirm payment', 'en', 'Confirm payment'),
('Bots', 'en', 'Bots'),
('Banned', 'en', 'Banned'),
('Active', 'en', 'Active'),
('Please, describe this item', 'en', 'Please, describe this item'),
('Description (e.g. Blue Nike Vapor Cleats Size 10. Very comfortable and strong ankle support.)', 'en', 'Description (e.g. Blue Nike Vapor Cleats Size 10. Very comfortable and strong ankle support.)'),
('Please, confirm item shipping address', 'en', 'Please, confirm item shipping address'),
('State', 'en', 'State'),
('City', 'en', 'City'),
('Zip code', 'en', 'Zip code'),
('Street', 'en', 'Street'),
('Phone number', 'en', 'Phone number'),
('Price', 'en', 'Price'),
('Choose action', 'en', 'Choose action'),
('Edit item', 'en', 'Edit item'),
('Deactivate item', 'en', 'Deactivate item'),
('Activate item', 'en', 'Activate item'),
('List new Item', 'en', 'List new Item'),
('Edit Properties', 'en', 'Edit Properties'),
('Keywords', 'en', 'Keywords'),
('Mode', 'en', 'Mode'),
('Replace', 'en', 'Replace'),
('Cron error', 'en', 'Cron error'),
('Save', 'en', 'Save'),
('Are you sure?', 'en', 'Are you sure?'),
('Add value', 'en', 'Add value'),
('Edit property', 'en', 'Edit property'),
('New value', 'en', 'New value'),
('Delete property', 'en', 'Delete property'),
('Add new property', 'en', 'Add new property'),
('Back to products', 'en', 'Back to products'),
('Connect with social network', 'en', 'Connect with social network'),
('Delivery confirmation', 'en', 'Delivery confirmation'),
('Quality', 'en', 'Quality'),
('Your comment here', 'en', 'Your comment here'),
('Purchases', 'en', 'Purchases'),
('Thank you for your order! Shipment in process now.', 'en', 'Thank you for your order! Shipment in process now.'),
('There is no purchases', 'en', 'There is no purchases'),
('Finances', 'en', 'Finances'),
('The funds have been added to your account', 'en', 'The funds have been added to your account'),
('Balance', 'en', 'Balance'),
('Pending', 'en', 'Pending'),
('New', 'en', 'New'),
('Transactions not found', 'en', 'Transactions not found'),
('Request withdrawal', 'en', 'Request withdrawal'),
('Confirm your PayPal', 'en', 'Confirm your PayPal'),
('Deposit money', 'en', 'Deposit money'),
('Amount to deposit', 'en', 'Amount to deposit'),
('About', 'en', 'About'),
('Products', 'en', 'Products'),
('Orders', 'en', 'Orders'),
('Finance', 'en', 'Finance'),
('Order products', 'en', 'Order products'),
('Confirmation', 'en', 'Confirmation'),
('Please, confirm your order', 'en', 'Please, confirm your order'),
('Remove product', 'en', 'Remove product'),
('Sorry, there is no products', 'en', 'Sorry, there is no products'),
('Total price', 'en', 'Total price'),
('Shipping', 'en', 'Shipping'),
('Please, confirm your shipping address', 'en', 'Please, confirm your shipping address'),
('Payment', 'en', 'Payment'),
('First name', 'en', 'First name'),
('Last name', 'en', 'Last name'),
('Country', 'en', 'Country'),
('Process payment', 'en', 'Process payment'),
('FILTER RESULTS', 'en', 'FILTER RESULTS'),
('Already have an account?', 'en', 'Already have an account?'),
('Empty search query', 'en', 'Empty search query'),
('Cart', 'en', 'Cart'),
('Withdrawal already requested', 'ru', 'Вывод средств уже запрошен'),
('Withdrawal request accepted', 'ru', 'Запрос на вывод средств принят'),
('Select file', 'ru', 'Выберите файл'),
('Editable file', 'ru', 'Редактируемый файл'),
('Source file', 'ru', 'Исходный файл'),
('Gateway Timeout', 'ru', 'Таймаут запроса'),
('Image too small. Minimal size is 400x400', 'ru', 'Изображение слишком маленькое. Минимальный размер 400x400'),
('Drop files here', 'ru', 'Пертащите файлы сюда'),
('System message', 'ru', 'Системное сообщение'),
('sign in', 'ru', 'авторизуйтесь'),
('Confirm Shipment', 'ru', 'Подтвердите отправку'),
('Post track number', 'ru', 'Почтовый трек-номер'),
('Shipment is confirmed', 'ru', 'Отправка подтверждена'),
('This item is sold out now?', 'ru', 'Снять товар с продажи?'),
('New order', 'ru', 'Новый заказ'),
('Archive order', 'ru', 'Архивировать заказ'),
('Finished', 'ru', 'Завершено'),
('Purchaser', 'ru', 'Покупатель'),
('Shipping address', 'ru', 'Адрес доставки'),
('All Items', 'ru', 'Все товары'),
('Buy Now!', 'ru', 'Купить!'),
('Title', 'ru', 'Название'),
('Ask price', 'ru', 'Стоимость'),
('Edit product', 'ru', 'Редактировать товар'),
('Click to Deactivate', 'ru', 'Деактивировать'),
('Click to Activate', 'ru', 'Активировать'),
('Buy Now', 'ru', 'Купить'),
('Tracking number', 'ru', 'Трек-номер'),
('Shipment in process', 'ru', 'Доставка в процессе'),
('Confirm receipt', 'ru', 'Подтвердить получение'),
('Seller', 'ru', 'Продавец'),
('Shipping from', 'ru', 'Доставка из'),
('New comment at', 'ru', 'Новый комментарий на'),
('Ok', 'ru', 'Ok'),
('New message at', 'ru', 'Новое сообщение на'),
('Dear', 'ru', 'Дорогой'),
('sent a message for you', 'ru', 'отправил(а) сообщение вам'),
('For details, click', 'ru', 'Для подробностей, кликните'),
('here', 'ru', 'здесь'),
('Withdrawal request at', 'ru', 'Вывод средств'),
('You withdrawal request is pending now', 'ru', 'Ваш запрос на вывод средств обрабатывается'),
('After some time you will receive', 'ru', 'Через некоторое время вам придет'),
('on your PayPal account', 'ru', 'на ваш PayPal аккаунт'),
('There in new withdrawal request at', 'ru', 'Новый запрос на вывод средств на'),
('Need to pay', 'ru', 'Нужно оплатить'),
('on PayPal account', 'ru', 'на PayPal аккаунт'),
('and confirm request', 'ru', 'и подтвредить запрос'),
('Details', 'ru', 'Подробности'),
('Withdrawal is complete at', 'ru', 'Вывод средств завершен на'),
('You withdrawal is complete', 'ru', 'Ваш запрос средств обработан'),
('Thanks for using our service and have a nice day', 'ru', 'Спасибо за использование нашего сервиса и удачного Вам дня'),
('New purchase at', 'ru', 'Новая покупка на'),
('Congratulations on your purchase at', 'ru', 'Поздравляем с покупкой на'),
('You can see details of your purchases', 'ru', 'Вы можете посмотреть подробную информацию о покупке'),
('There in new purchase at', 'ru', 'Новая покупка на'),
('make a payment', 'ru', 'совершил платеж'),
('to your PayPal account', 'ru', 'на ваш PayPal аккаунт'),
('Your order has been shipped at', 'ru', 'Ваш заказ был отправлен на'),
('Your order', 'ru', 'Ваш заказ'),
('has been shipped', 'ru', 'был отправлен'),
('After receiving, please update purchase status', 'ru', 'После получения обновите статус покупки'),
('Your order has been completed at', 'ru', 'Ваш заказ был завершен на'),
('Your order has been completed', 'ru', 'Ваш заказ был завершен'),
('Funds added to your account and available for withdrawal', 'ru', 'Средства зачислены на Ваш аккаунт и доступны для вывода'),
('Orders not found', 'ru', 'Заказов не найдено'),
('Type', 'ru', 'Тип'),
('Withdrawal request', 'ru', 'Запрос на вывод'),
('Money deposit', 'ru', 'Зачисление средств'),
('Order', 'ru', 'Заказ'),
('Please, confirm transaction', 'ru', 'Пожалуйста, подтвердите'),
('Confirm payment', 'ru', 'Подтвердить платеж'),
('Bots', 'ru', 'Боты'),
('Banned', 'ru', 'Забанен'),
('Active', 'ru', 'Активен'),
('Please, describe this item', 'ru', 'Пожалуйста, опишите товар'),
('Description (e g  Blue Nike Vapor Cleats Size 10  Very comfortable and strong ankle support )', 'ru', 'Описание (прим. Синиие Nike Vapor Бутсы. Размер 10. Очень удобные и сильная поддержка лодыжки.)'),
('Please, confirm item shipping address', 'ru', 'Пожалуйста, подтвердите адрес'),
('State', 'ru', 'Область'),
('City', 'ru', 'Город'),
('Zip code', 'ru', 'Почтовый индекс'),
('Street', 'ru', 'Улица'),
('Phone number', 'ru', 'Номер телефона'),
('Price', 'ru', 'Цена'),
('Choose action', 'ru', 'Выберете действие'),
('Edit item', 'ru', 'Редактировать товар'),
('Deactivate item', 'ru', 'Деактивировать'),
('Activate item', 'ru', 'Активировать'),
('List new Item', 'ru', 'Добавить новый товар'),
('Edit Properties', 'ru', 'Редактировать свойства'),
('Keywords', 'ru', 'Ключевые слова'),
('Mode', 'ru', 'Режим'),
('Replace', 'ru', 'Заменить'),
('Cron error', 'ru', 'Ошибка cron'),
('Save', 'ru', 'Сохранить'),
('Are you sure?', 'ru', 'Вы уверены?'),
('Add value', 'ru', 'Добавить значение'),
('Edit property', 'ru', 'Редактировать свойство'),
('New value', 'ru', 'Новое значение'),
('Delete property', 'ru', 'Удалить свойство'),
('Add new property', 'ru', 'Добавить новое свойство'),
('Back to products', 'ru', 'Назад к товарам'),
('Connect with social network', 'ru', 'Подключить аккаунт соц. сети'),
('Delivery confirmation', 'ru', 'Подтверждение получения'),
('Quality', 'ru', 'Качество'),
('Your comment here', 'ru', 'Ваш комментарий'),
('Purchases', 'ru', 'Покупки'),
('Thank you for your order! Shipment in process now.', 'ru', 'Спасибо за Ваш заказ! Отправление в процессе.'),
('There is no purchases', 'ru', 'Нет новых покупок'),
('Finances', 'ru', 'Финансы'),
('The funds have been added to your account', 'ru', 'Средства были зачислены на Ваш аккаунт'),
('Balance', 'ru', 'Баланс'),
('Pending', 'ru', 'Ожидание'),
('New', 'ru', 'Новый'),
('Transactions not found', 'ru', 'Транзакций не найдено'),
('Request withdrawal', 'ru', 'Запрос на вывод'),
('Confirm your PayPal', 'ru', 'Укажите Ваш PayPal'),
('Deposit money', 'ru', 'Зачислить средства'),
('Amount to deposit', 'ru', 'Количество к зачислению'),
('About', 'ru', 'О программе'),
('Products', 'ru', 'Товары'),
('Orders', 'ru', 'Заказы'),
('Finance', 'ru', 'Финансы'),
('Order products', 'ru', 'Заказать товары'),
('Confirmation', 'ru', 'Подтверждение'),
('Please, confirm your order', 'ru', 'Пожалуйста, подтвердите Ваш заказ'),
('Remove product', 'ru', 'Удалить товар'),
('Sorry, there is no products', 'ru', 'Извините, товаров не найдено'),
('Total price', 'ru', 'Итоговая цена'),
('Shipping', 'ru', 'Доставка'),
('Please, confirm your shipping address', 'ru', 'Пожалуйста, подтвержите адрес'),
('Payment', 'ru', 'Платеж'),
('First name', 'ru', 'Имя'),
('Last name', 'ru', 'Фамилия'),
('Country', 'ru', 'Страна'),
('Process payment', 'ru', 'Оплатить'),
('FILTER RESULTS', 'ru', 'ФИЛЬТР РЕЗУЛЬТАТОВ'),
('Already have an account?', 'ru', 'Уже зарегистрированы?'),
('Empty search query', 'ru', 'Пустой поисковый запрос'),
('Cart', 'ru', 'Корзина'),
('Description (e.g. Blue Nike Vapor Cleats Size 10. Very comfortable and strong ankle support.)', 'ru', 'Описание (прим. Синиие Nike Vapor Бутсы. Размер 10. Очень удобные и сильная поддержка лодыжки.)'),
('Views per day', 'ru', 'Просмотров в день'),
('Last visit', 'en', 'Last visit'),
('b', 'ru', 'Ваш заказ был завершен'),
('Visitors per day', 'ru', 'Посетителей в день'),
('Total comments', 'ru', 'Всего комментариев'),
('Total users', 'ru', 'Всего пользователей'),
('Total articles', 'ru', 'Всего статей'),
('Total products', 'ru', 'Всего товаров'),
('Total pages', 'ru', 'Всего страниц'),
('Engine version', 'ru', 'Версия движка'),
('Delete article', 'ru', 'Удалить статью'),
('Page generation time', 'ru', 'Скорость генерации страницы'),
('Select an action', 'ru', 'Выберите действие'),
('Up to top', 'ru', 'Поднять вверх'),
('Transaction completed', 'ru', 'Перевод завершен'),
('Transaction from admin', 'ru', 'Перевод от админа'),
('New transaction', 'ru', 'Сделать перевод'),
('Transfer amount', 'ru', 'Сумма перевода'),
('This is a daily report for the website traffic and performance on', 'ru', 'Это дневной отчет о посещаемости и нагрузки на сайт'),
('Thanks for using our service', 'ru', 'Спасибо за использование нашего сервиса'),
('daily report', 'ru', 'дневной отчет'),
('Under construction', 'ru', 'В разработке'),
('Time', 'ru', 'Время'),
('Continue shopping', 'ru', 'Продолжить покупки'),
('Process order?', 'ru', 'Оформить заказ?'),
('A new item has been added to your Shopping Cart', 'ru', 'Новый товар был добавлен в корзину'),
('item(s)', 'ru', 'товар(ов)'),
('Your Shopping Cart', 'ru', 'Ваша корзина'),
('Checkout order', 'ru', 'Оформить заказ'),
('Navigation', 'ru', 'Навигация'),
('Profile image', 'ru', 'Изображение профиля'),
('Page generation speed', 'ru', 'Скорость генерации страниц'),
('By hours', 'ru', 'По часам'),
('Average Server Response', 'ru', 'Среднее время ответа сервера'),
('Average Site Response', 'ru', 'Среднее время ответа сайта'),
('Perfomance', 'ru', 'Нагрузка'),
('The user makes a purchase', 'ru', 'Пользователь сделал покупку'),
('User confirmed the receipt of the order', 'ru', 'Пользователь подтвердил получение заказа'),
('Order has been shipped', 'ru', 'Заказ был отправлен'),
('The user makes a purchase and payment!', 'ru', 'Пользователь сделал покупку с оплатой!'),
('Checkout order?', 'ru', 'Оформить заказ?'),
('Drop file here', 'ru', 'Перетащите сюда файл'),
('Uploading', 'ru', 'Загрузка'),
('Open', 'ru', 'Открыть'),
('The funds', 'ru', 'Средства'),
('has beed added to your account balance', 'ru', 'были зачислины на счет Вашего аккаунта'),
('this link', 'ru', 'эту ссылку'),
('To confirm this password, use', 'ru', 'Для подтверждения пароля, используйте'),
('Close window', 'ru', 'Закрыть окно'),
('Sorry, this email already registered', 'ru', 'Извините, этот email уже зарегистрирован'),
('The funds have been added to your account balance', 'ru', 'Средства были зачислены на Ваш счет'),
('New password activated!', 'ru', 'Новый пароль активирован!'),
('already exist', 'ru', 'уже существует'),
('Checkout order?', 'en', 'Checkout order?'),
('Error! Drag-n-drop disabled on this server', 'en', 'Error! Drag-n-drop disabled on this server'),
('Uploading', 'en', 'Uploading'),
('Drop file here', 'en', 'Drop file here'),
('Error! Drag-n-drop disabled on this server', 'ru', 'Ошибка. Функция перетаскивания отключена'),
('The user makes a purchase and payment!', 'en', 'The user makes a purchase and payment!'),
('Order has been shipped', 'en', 'Order has been shipped'),
('User confirmed the receipt of the order', 'en', 'User confirmed the receipt of the order'),
('The user makes a purchase', 'en', 'The user makes a purchase'),
('online', 'en', 'online'),
('Perfomance', 'en', 'Perfomance'),
('By hours', 'en', 'By hours'),
('Average Server Response', 'en', 'Average Server Response'),
('Average Site Response', 'en', 'Average Site Response'),
('Page generation speed', 'en', 'Page generation speed'),
('Profile image', 'en', 'Profile image'),
('Navigation', 'en', 'Navigation'),
('Checkout order', 'en', 'Checkout order'),
('Your Shopping Cart', 'en', 'Your Shopping Cart'),
('item(s)', 'en', 'item(s)'),
('Process order?', 'en', 'Process order?'),
('A new item has been added to your Shopping Cart', 'en', 'A new item has been added to your Shopping Cart'),
('Continue shopping', 'en', 'Continue shopping'),
('Time', 'en', 'Time'),
('Under construction', 'en', 'Under construction'),
('daily report', 'en', 'daily report'),
('Thanks for using our service', 'en', 'Thanks for using our service'),
('This is a daily report for the website traffic and performance on', 'en', 'This is a daily report for the website traffic and performance on'),
('Transfer amount', 'en', 'Transfer amount'),
('New transaction', 'en', 'New transaction'),
('Transaction completed', 'en', 'Transaction completed'),
('Transaction from admin', 'en', 'Transaction from admin'),
('Page generation time', 'en', 'Page generation time'),
('Select an action', 'en', 'Select an action'),
('Up to top', 'en', 'Up to top'),
('Delete article', 'en', 'Delete article'),
('Engine version', 'en', 'Engine version'),
('Total pages', 'en', 'Total pages'),
('Total articles', 'en', 'Total articles'),
('Total products', 'en', 'Total products'),
('Total users', 'en', 'Total users'),
('Total comments', 'en', 'Total comments'),
('Visitors per day', 'en', 'Visitors per day'),
('Views per day', 'en', 'Views per day'),
('Cron status', 'ru', 'Cron статус'),
('Cache', 'ru', 'Кеш'),
('Any action', 'ru', 'Любое действие'),
('Email sended', 'ru', 'Email отправлен'),
('Empty', 'ru', 'Пусто'),
('Last visit', 'ru', 'Последний визит'),
('Profile', 'ru', 'Профиль'),
('Continue', 'ru', 'Продолжить'),
('Checkout', 'ru', 'Оформить'),
('Edit catalog', 'ru', 'Редактировать каталог'),
('Delete catalog', 'ru', 'Удалить каталог'),
('Articles', 'ru', 'Статьи'),
('Down to bottom', 'ru', 'Опустить вниз'),
('List articles', 'ru', 'Список статей'),
('User banned', 'ru', 'Пользователь забанен'),
('Show more', 'en', 'Show more'),
('Privacy Policy', 'en', 'Privacy Policy'),
('Terms & Conditions', 'en', 'Terms & Conditions'),
('Any', 'en', 'Any'),
('Outbox', 'en', 'Outbox'),
('Continue', 'en', 'Continue'),
('Checkout', 'en', 'Checkout'),
('Show comments', 'en', 'Show comments'),
('Latest comments', 'en', 'Latest comments'),
('Show more', 'ru', 'Показать остальные'),
('Privacy Policy', 'ru', 'Конфиденциальность'),
('Terms & Conditions', 'ru', 'Правила и условия'),
('Any', 'ru', 'Любой'),
('Outbox', 'ru', 'Рассылка'),
('Show comments', 'ru', 'Показать комментарии'),
('Latest comments', 'ru', 'Последние комментарии'),
('View source', 'en', 'View source'),
('Delete file', 'en', 'Delete file'),
('Delete template', 'en', 'Delete template'),
('View source', 'ru', 'Посмотреть исходник'),
('Delete file', 'ru', 'Удалить файл'),
('Delete template', 'ru', 'Удалить шаблон'),
('Articles', 'en', 'Articles'),
('Member of', 'en', 'Member of'),
('community', 'en', 'community'),
('Property', 'en', 'Property'),
('Copy to', 'en', 'Copy to'),
('translation', 'en', 'translation'),
('Member of', 'ru', 'Участник '),
('community', 'ru', 'комьюнити'),
('Property', 'ru', 'Свойство'),
('Copy to', 'ru', 'Скопировать в'),
('translation', 'ru', 'перевод'),
('Color', 'en', 'Color'),
('White', 'en', 'White'),
('Black', 'en', 'Black'),
('Silver', 'en', 'Silver'),
('Gray', 'en', 'Gray'),
('Color', 'ru', 'Цвет'),
('White', 'ru', 'Белый'),
('Black', 'ru', 'Черный'),
('Silver', 'ru', 'Серебристый'),
('Gray', 'ru', 'Серый'),
('New bulk message', 'en', 'New bulk message'),
('Profile', 'en', 'Profile'),
('Ok', 'en', 'Ok'),
('Cron status', 'en', 'Cron status'),
('Cache', 'en', 'Cache'),
('List articles', 'en', 'List articles'),
('Edit catalog', 'en', 'Edit catalog'),
('Delete catalog', 'en', 'Delete catalog');