/* Nodes Studio system file. Do not edit! */var ua=navigator.userAgent.toLowerCase(),isOpera=-1<ua.indexOf("opera"),isIE=!isOpera&&-1<ua.indexOf("msie");function getBodyScrollTop(){return self.pageYOffset||document.documentElement&&document.documentElement.scrollTop||document.body&&document.body.scrollTop}function getDocumentHeight(){return Math.max("CSS1Compat"!=document.compatMode?document.body.scrollHeight:document.documentElement.scrollHeight,getViewportHeight())}
function getDocumentWidth(){return Math.max("CSS1Compat"!=document.compatMode?document.body.scrollWidth:document.documentElement.scrollWidth,getViewportWidth())}function getViewportHeight(){return!document.compatMode&&!isIE||isOpera?(document.parentWindow||document.defaultView).innerHeight:"CSS1Compat"==document.compatMode?document.documentElement.clientHeight:document.body.clientHeight}
function getViewportWidth(){return!document.compatMode&&!isIE||isOpera?(document.parentWindow||document.defaultView).innerWidth:"CSS1Compat"==document.compatMode?document.documentElement.clientWidth:document.body.clientWidth}function getXmlHttp(){var a;try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(d){a=!1}}a||"undefined"==typeof XMLHttpRequest||(a=new XMLHttpRequest);return a}
function addHandler(a,b,d,c){a.addEventListener?a.addEventListener(b,d,c?c:!1):a.attachEvent?a.attachEvent("on"+b,d):alert("Add handler is not supported")}function setCookie(a,b,d){d=d||{};var c=d.expires;if("number"==typeof c&&c){var e=new Date;e.setTime(e.getTime()+1E3*c);c=d.expires=e}c&&c.toUTCString&&(d.expires=c.toUTCString());b=encodeURIComponent(b);a=a+"="+b;for(var f in d)a+="; "+f,b=d[f],!0!==b&&(a+="="+b);document.cookie=a}
function readCookie(a){a+="=";for(var b=document.cookie.split(";"),d=0;d<b.length;d++){for(var c=b[d];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return null}function js_show_wnd(a){if(a&&"undefined"!=a){disableScroll();parent.document.body.style.overflow="hidden";var b=parent.document.createElement("div");b.id="nodes_window";b.innerHTML=a;parent.document.body.appendChild(b);addSiteFade()}else js_hide_wnd()}
function js_pos_wnd(){parent.document.getElementById("nodes_window").style.top=(getViewportHeight()-parent.document.getElementById("nodes_window").clientHeight)/2+"px"}function js_hide_wnd(){enableScroll();parent.document.body.style.overflow="auto";parent.document.body.removeChild(parent.document.getElementById("nodes_window"));removeSiteFade()}function empty(a){return""===a||0===a||"0"===a||null===a||!1===a||is_array(a)&&0===a.length}
function show_login_form(){try{hideMenu(),scrolltoTop()}catch(a){}parent.document.getElementById("nodes_window")&&js_hide_wnd();js_show_wnd('<div style="float:right; margin-top: -15px; margin-right: -15px;"><img style="cursor:pointer;" onClick=\'js_hide_wnd();\' title="Close window" src="'+root_dir+'/img/x.png" width=15 height=15 /></div><img src="'+root_dir+'/img/load.gif" id="loader"><iframe frameborder=0 style="display:none;" width=200 height=260 id="nodes_iframe" src="'+root_dir+'/account.php" onLoad=\'document.getElementById("loader").style.display="none";this.style.display="block";js_pos_wnd();addHandler(window, "resize", js_pos_wnd);\'></iframe>')}
function logout(){try{scrolltoTop()}catch(a){}js_show_wnd('<img src="'+root_dir+'/img/load.gif" id="loader"><iframe frameborder=0 style="display:none;" width=1 height=1 id="nodes_iframe" src="'+root_dir+'/account.php?mode=logout"></iframe>')}var keys={37:1,38:1,39:1,40:1};function preventDefault(a){a=a||window.event;a.preventDefault&&a.preventDefault();a.returnValue=!1}function preventDefaultForScrollKeys(a){if(keys[a.keyCode])return preventDefault(a),!1}
function disableScroll(){window.addEventListener&&window.addEventListener("DOMMouseScroll",preventDefault,!1);window.onwheel=preventDefault;window.onmousewheel=document.onmousewheel=preventDefault;window.ontouchmove=preventDefault;document.onkeydown=preventDefaultForScrollKeys}
function enableScroll(){window.removeEventListener&&window.removeEventListener("DOMMouseScroll",preventDefault,!1);window.onmousewheel=document.onmousewheel=null;window.onwheel=null;window.ontouchmove=null;document.onkeydown=null}
function base64_decode(a){var b,d,c,e,f,g=0,h="";do b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(g++)),c=b<<18|d<<12|e<<6|f,b=c>>16&255,d=c>>8&255,c&=255,h=64==e?h+String.fromCharCode(b):
64==f?h+String.fromCharCode(b,d):h+String.fromCharCode(b,d,c);while(g<a.length);return h}
function show_editor(a){if(content&&"undefined"!=content){window.scrollTo(0,0);disableScroll();parent.document.body.style.overflow="hidden";var b=parent.document.createElement("div");b.id="editor_window";b.innerHTML='<div style="float:left;margin-top: -10px;"><b>'+a+'</b></div><div style="float:right; margin-top: -10px; margin-right: -10px;"><img style="cursor:pointer;" onClick=\'hide_editor();\' title="Close window" src="'+root_dir+'/img/x.png" width=15 height=15 /></div><br/><iframe width=100% height=100% frameborder=0 src="'+
root_dir+"/edit.php?file="+a+'" />';parent.document.body.appendChild(b);addSiteFade()}else hide_editor()}function hide_editor(){enableScroll();parent.document.body.style.overflow="auto";parent.document.body.removeChild(parent.document.getElementById("editor_window"));removeSiteFade()};